### ISSUE TITLE
OpenSCAD executable unavailable

### ISSUE THREAD

**Issue by tegger2000** [KeithSloan/OpenSCAD_Alt_Import#4]
i got the error on MacOS:
20:14:47  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tegger/Library/Preferences/FreeCAD/Mod/OpenSCAD_Alt_Import/freecad/OpenSCAD_Alt_Import/importCSG.py", line 90, in open
    tmpfile=callopenscad(filename)
  File "/Users/tegger/Library/Preferences/FreeCAD/Mod/OpenSCAD_Alt_Import/OpenSCADUtils.py", line 186, in callopenscad
    raise OpenSCADError('OpenSCAD executable unavailable')
<class 'OpenSCADUtils.OpenSCADError'>: 'OpenSCAD executable unavailable'

i installed OpenSCAD with brew. I didn't find a parameter for the importer, so how could i fix that ?

**Comment by tegger2000** [comment]
okay, i found it. You need to replace
 <FCParamGroup Name="OpenSCAD"  />
with
<FCParamGroup Name="OpenSCAD">
            <FCText Name="openscadexecutable">/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD</FCText>
          </FCParamGroup>
in the user.cfg. It's in ~/Library/Preferences/FreeCAD/

**Comment by Nick-Z0** [comment]
Did not work for me. Below are the errors it threw for each of the available import options if anyone is interested. I found it easier to remake the object I wanted.

```
22:30:01  Verbose = False
22:30:01  Processing : /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:30:01  Calling OpenSCAD
22:30:01  Using Alternate OpenSCAD Importer
22:30:01  Doc Triomino_engraved useMaxFn 16
22:30:01  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 100, in open
    processCSG(doc, tmpfile)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 175, in processCSG
    result = parser.parse(f.read())
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1356, in p_text_action
    t = addString(t,'script',p)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1339, in addString
    return(t + ', ' +s+' = "'+p[3][s]+'"')
<class 'KeyError'>: 'script'
22:32:50  Verbose = False
22:32:50  Creating SCAD File Object from : /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:32:50  Create SCAD File Object Triomino_engraved path /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:32:50  Triomino_engraved State : ['Touched'] prop : Proxy
22:32:50  create Geometry
22:32:50  Do not process SCAD source on Document recompute
22:32:50  View Provider OnChanged : prop DisplayMode
22:32:50  View Provider OnChanged : prop DisplayMode
22:32:50  View Provider OnChanged : prop DisplayMode
22:32:50  View Provider OnChanged : prop Proxy
22:32:50  Execute Triomino_engraved keepWork False
22:32:50  shapeFrom Source File : keepWork False
22:32:50  Create Brep Triomino_engraved.scad 16
22:32:50  Active Document Triomino_engraved
22:32:50  Source : Triomino_engraved.scad
22:32:50  SourceFile : /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:32:50  <Document object at 0x7fd82c3a3c00>
22:32:50  Before :  Can't open input file '/var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T/Triomino_engraved.scad'!
22:32:50  
22:32:50  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importFileSCAD.py", line 65, in open
    obj.Proxy.executeFunction(obj)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 273, in executeFunction
    shp = shapeFromSourceFile(obj, modules = obj.modules)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 178, in shapeFromSourceFile
    brepShape = createBrep(srcObj, tmpDir, wrkSrc)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 126, in createBrep
    after = e.value.rsplit(',',1)[1]
<class 'IndexError'>: list index out of range
22:33:18  Verbose = False
22:33:18  Creating Object from : /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:33:18  Create Object Triomino_engraved path /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:33:18  Triomino_engraved001 State : ['Touched'] prop : Proxy
22:33:18  create Geometry
22:33:18  Do not process SCAD source on Document recompute
22:33:18  Doc temp dir /var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T
22:33:18  Path /var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T/Triomino_engraved001.scad
22:33:18  Copy File /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad /var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T/Triomino_engraved001.scad
22:33:18  Triomino_engraved001 State : ['Touched'] prop : sourceFile
22:33:18  View Provider OnChanged : prop DisplayMode
22:33:18  View Provider OnChanged : prop DisplayMode
22:33:18  View Provider OnChanged : prop DisplayMode
22:33:18  View Provider OnChanged : prop Proxy
22:33:18  Execute Triomino_engraved001 keepWork False
22:33:18  shapeFrom Source File : keepWork False
22:33:18  Create Brep Triomino_engraved001.scad 16
22:33:18  Active Document Triomino_engraved
22:33:18  Source : Triomino_engraved001.scad
22:33:18  SourceFile : /var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T/Triomino_engraved001.scad
22:33:18  <Document object at 0x7fd83c6ec800>
22:33:18  CSG File name /var/folders/5l/8z4lqvmn5_n_x15dq00rzt400000gn/T/Triomino_engraved001.csg
22:33:18  Using Alternate OpenSCAD Importer
22:33:18  Doc work useMaxFn 16
22:33:18  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importSCAD.py", line 67, in open
    obj.Proxy.executeFunction(obj)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 273, in executeFunction
    shp = shapeFromSourceFile(obj, modules = obj.modules)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 178, in shapeFromSourceFile
    brepShape = createBrep(srcObj, tmpDir, wrkSrc)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCADObjects.py", line 87, in createBrep
    processCSG(wrkDoc, tmpFileName, srcObj.fnmax)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 175, in processCSG
    result = parser.parse(f.read())
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1356, in p_text_action
    t = addString(t,'script',p)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1339, in addString
    return(t + ', ' +s+' = "'+p[3][s]+'"')
<class 'KeyError'>: 'script'
22:33:29  Processing : /Users/User/Downloads/3D models/Triomino_Parametric_Engraved_5408529/files/Triomino_engraved.scad
22:33:29  Calling OpenSCAD
22:33:29  Using Alternate OpenSCAD Importer
22:33:29  Doc Triomino_engraved1 useMaxFn 16
22:33:29  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 100, in open
    processCSG(doc, tmpfile)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 175, in processCSG
    result = parser.parse(f.read())
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1356, in p_text_action
    t = addString(t,'script',p)
  File "/Users/User/Library/Application Support/FreeCAD/Mod/Alternate_OpenSCAD/./importCSG.py", line 1339, in addString
    return(t + ', ' +s+' = "'+p[3][s]+'"')
<class 'KeyError'>: 'script'
```

**Comment by KeithSloan** [comment]
What happens when you try the standard importer!!! ? i.e The OpenSCAD Workbench.

The Alternate importer does not use a different method or obtaining the location of the OpenSCAD executable.

I might be wrong but my suspicion is there is a problem with the OpenSCAD Workbench settings.

**Comment by KeithSloan** [comment]
Nick-Z0

Your error was not a OpenSCAD executable unavailable but a bug with Fix bug with ScadFileObject (importFileSCAD) and modules=True property'

Should be fixed in latest version.

**Comment by KeithSloan** [comment]
You are also getting an error on parsing a OpenSCAD **text** function, please could you supply the SCAD source you are using or the saved FreeCAD file when you use SCADObject import.

**Comment by Nick-Z0** [comment]
The file is here: https://www.thingiverse.com/thing:5408529
There is only one scad file. I could not upload this filetype here.

**Comment by Nick-Z0** [comment]
> What happens when you try the standard importer!!! ? i.e The OpenSCAD Workbench.
> 
> The Alternate importer does not use a different method or obtaining the location of the OpenSCAD executable.
> 
> I might be wrong but my suspicion is there is a problem with the OpenSCAD Workbench settings.

I think it is more of a setup problem from my side. I did not find the original workbench and after I found it and tried it, there was a library missing (DXF) etc. It is my first time using this program so I did not know what to do.

**Comment by KeithSloan** [comment]
Suggest you uninstall the Alternate OpenSCAD importer - Use FreeCAD | Tools | Addon Manager
Scroll to Alternate OpenSCAD workbench an **uninstall.**

Try with the standard OpenSCAD importer i.e. Just try and import the file.

You have to Activate the OpenSCAD work bench.
Click On FreeCAD | Preferences

Should see a screen like this

![Image 22-02-2023 at 22 44](https://user-images.githubusercontent.com/2291247/220777345-0c8fd2e5-72f9-4b01-9682-55e7055292b5.jpg)

Click on the OpenSCAD icon in the left hand column
![Image 22-02-2023 at 22 45](https://user-images.githubusercontent.com/2291247/220777489-514abf12-7a0d-49e2-be70-ca47e7f13113.jpg)

Should now see 

![Image 22-02-2023 at 22 46](https://user-images.githubusercontent.com/2291247/220777594-c1398b13-d978-484e-aad3-64ace281dfc2.jpg)

You then need to tell it where OpenSCAD is installed.

I would the restart FreeCAD just to be on the safe side.
Then try and import your file.

File | Open 

When you have the standard importer working then try and reinstall the Alternate OpenSCAD importer

FreeCAD | Tools | Addon Manager - etc.

**Comment by KeithSloan** [comment]
Nick-Z0

Thanks for reporting the problem

I can recreate your problem, it also occurs on the FreeCAD OpenSCAD workbench importer, I have made some small fixes so things get further i.e. It successfully imports the DXF file that is created but there is a bug in the clean up of layers. I have PM's Chris Hennes for his thoughts, as he has been maintaining the main importer.

**Comment by KeithSloan** [comment]
Have pushed updates to repro.

Triomino_engraved.scad now imports
[Triomino_engraved.FCStd.txt](https://github.com/KeithSloan/OpenSCAD_Alt_Import/files/10809365/Triomino_engraved.FCStd.txt)
